apple=int(input("Enter the apple cost:"))
orange=int(input("Enter the orange cost:"))
graphs=int(input("Enter the graphs cost:"))
fruit=open("menu.txt", "a")
fruit.write(str(apple)+'|')
fruit.write(str(orange)+'|')
fruit.write(str(graphs)+ '\n')
fruit.close()
priya=open("menu.txt","r")
read=(priya.read())
print(read)
priya.close()
