# -*- coding: utf-8 -*-
"""withmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nu5JwwErGNN3mxMbMtXmtqESudmsi4cH
"""

# Install HuggingFace Transformers
!pip install transformers

# Import required libraries
from transformers import pipeline

from google.colab import drive
drive.mount('/content/drive')

# Load a conversational model
chatbot = pipeline("text-generation", model="gpt2")

# Function to generate responses
def generate_response(user_input):
    response = chatbot(user_input, max_length=100, num_return_sequences=1, do_sample=True)
    return response[0]['generated_text']

# Start a chat loop
print("Welcome to the Career Guidance Chatbot! Type 'exit' to quit.\n")

while True:
    user_input = input("You: ")
    if user_input.lower() == "exit":
        print("Goodbye!")
        break
    response = generate_response(user_input)
    print(f"Chatbot: {response}\n")



!pip install transformers

# Install and import required libraries
!pip install transformers

from transformers import pipeline

# Load a pre-trained conversational model (DialoGPT)
chatbot = pipeline("conversational", model="microsoft/DialoGPT-medium")

def chat_with_bot():
    print("Welcome to the Career Guidance Chatbot! Type 'exit' to end the chat.\n")
    while True:
        # Take user input
        user_input = input("You: ")
        if user_input.lower() == "exit":
            print("Goodbye!")
            break

        # Generate chatbot response
        try:
            response = chatbot(user_input)
            print(f"Chatbot: {response['generated_text']}\n")
        except Exception as e:
            print(f"Error: {e}")
            break

# Run the chatbot
chat_with_bot()

# Install and import required libraries
!pip install transformers

from transformers import pipeline

# Load a pre-trained text-generation model (GPT-2)
chatbot = pipeline("text-generation", model="gpt2")

def chat_with_bot():
    print("Welcome to the Career Guidance Chatbot! Type 'exit' to end the chat.\n")
    while True:
        # Take user input
        user_input = input("You: ")
        if user_input.lower() == "exit":
            print("Goodbye!")
            break

        # Generate chatbot response
        try:
            response = chatbot(user_input, max_length=50, num_return_sequences=1)
            print(f"Chatbot: {response[0]['generated_text']}\n")
        except Exception as e:
            print(f"Error: {e}")
            break

# Run the chatbot
chat_with_bot()